orders plugin graphql docs
reactioncommerce/docs pull request #19
Opened 2021-09-22 20:27 UTC by MohanNarayana

Signed-off-by: Mohan Narayana <mohan.narayana@mailchimp.com>

2021-10-11 17:39 UTC, delagroove commented on docs/orders.md
> +Orders plugin deals with order creation, fetching orders by order ID, reference ID or payment ID, cancelling order, refunds.
'and refunds.' sound best

2021-10-11 19:31 UTC, MohanNarayana commented on docs/orders.md
> +Orders plugin deals with order creation, fetching orders by order ID, reference ID or payment ID, cancelling order, refunds.
Done

2021-10-15 18:58 UTC, delagroove requested changes

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +Orders plugin deals with order creation, fetching orders by order ID, reference ID or payment ID, cancelling order, refunds.
@MohanNarayana

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +- surcharges: [AppliedSurcharge]!
add def

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +Query the Orders collection for an order. It requires both orderId (as id) and shopId as query parameters. A token string can be used as a parameter for annonymous orders not linked with an account.
typo

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +Query the Orders collection for an order. It requires both referenceId (as id) and shopId as query parameters. A token string can be used as a parameter for annonymous orders not linked with an accou
typo

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +Query the Orders collection for an order. It requires both referenceId (as id) and shopId as query parameters. A token string can be used as a parameter for annonymous orders not linked with an accou
id vs is

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +1. **addOrderFulfillmentGroup** : Use this mutation to add a new order fulfillment group to an order. It must have at least one item, which can be provided or moved from another existing group. The b
typo fulfillment

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +4. **moveOrderItems** : This mutation is used to change the fulfillment group of an order. Each fulfillment group has atlease one fulfillment type and the fulfillment type describes the method of del
typo at least

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +5. **placeOrder** : Used it place the final order. The input for this mutation `PlaceOrderInput` takes order and payments information. The order will be placed only if authorization is successful for
typo

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +6. **sendOrderEmail** : A mutation that compiles and server-side renders the email template with order data, and sends the email. Email is triggered upon creation of order, when shipped, creation of
remove one refund

2021-10-15 18:58 UTC, delagroove commented on docs/orders.md
> +7. **splitOrderItem** : Use this mutation to reduce the quantity of one item of an order and create a new item for the remaining quantity in the same fulfillment group, and with the same item status.
typo

2022-01-05 03:17 UTC, zenweasel commented
I think everything here should just be in the GraphQL schema. One of the big pluses of GraphQL is that it is self-documenting so I think having this copied to another place just creates a maintenance issue. I would suggest we just double-check that all this information is in the schema itself and then close it.

2022-01-05 19:29 UTC, delagroove commented
Actually i have checked the docs and we brought that info from there. closing.

2022-01-05 19:29 UTC, closed without merging