feat: add how to create a tax plugin
reactioncommerce/docs pull request #38
Opened 2022-01-04 05:45 UTC by zenweasel

Signed-off-by: Brent Hoover <brent@thebuddhalodge.com>

Updates from old docs:

Changed title to correct format
Removed non-existent links
Linked to existing example tax plugin
Removed references to React component
Corrected call signature for `calculateOrderTaxes` (includes cart)
Double-checked that return payload is still the same

2022-01-05 20:24 UTC, MohanNarayana requested changes

2022-01-05 20:24 UTC, MohanNarayana commented on how-tos/create-a-tax-plugin.md
> +- Understanding how to create and integrate a plugin
Maybe we can add a link to create plugin here.

2022-01-05 20:24 UTC, MohanNarayana commented on how-tos/create-a-tax-plugin.md
> +  taxRate: 3.5, // The tax rate for this type of tax, used for this calculation
Also mention that the value is a percentage.

2022-01-05 22:48 UTC, delagroove approved these changes

2022-01-20 07:44 UTC, zenweasel commented
@MohanNarayana Changes from c/r made

2022-02-07 05:16 UTC, zenweasel commented
replaced by #67

2022-02-07 05:16 UTC, closed without merging