feat: add how to create address-validation service plugin doc
reactioncommerce/docs pull request #40
Opened 2022-01-04 08:01 UTC by zenweasel

Signed-off-by: Brent Hoover <brent@thebuddhalodge.com>

Updated from old doc:

Added "Background" on why would want an address validation service
Updated and validated the shape of the call
Updated internal doc links (one link to a doc yet to be created marked FIXME)

2022-01-05 22:39 UTC, delagroove approved these changes

2022-01-07 19:22 UTC, MohanNarayana requested changes

2022-01-07 19:22 UTC, MohanNarayana commented on how-tos/create-an-address-validation-service.md
> +Many types of services such as tax or shipping require that the address be validated so that they know the prices/rates they are quoting
Remove line breaks.

2022-01-20 07:50 UTC, zenweasel commented
@MohanNarayana Changes from C/R made

2022-02-14 02:03 UTC, delagroove requested changes

2022-02-14 02:03 UTC, delagroove commented on guides/create-an-address-validation-service.md
> +Having accurate address information is a critical part of marking sure your customers' product arrives on time and is delivered to the
add spacing

2022-02-14 02:03 UTC, delagroove commented on guides/create-an-address-validation-service.md
> +- [Understanding Plugins](/developer/open-commerce/guides/build-api-plugin/)
add spacing

2022-02-14 02:03 UTC, delagroove commented on guides/create-an-address-validation-service.md
> +More than likely your validation solution returns similar data but in a different schema. In this case you'll need to create a transform function to normalize the data structure for the query. See th
add spacing

2022-02-14 02:03 UTC, delagroove commented on guides/create-an-address-validation-service.md
> +More than likely your validation solution returns similar data but in a different schema. In this case you'll need to create a transform function to normalize the data structure for the query. See th
in h2

2022-02-14 02:03 UTC, delagroove commented on guides/quick-start.md
> +- Open Commerce API (port 3000), including the [core plugins](/developer/open-commerce/docs/plugins-environment-variables/#plugins). This service also contains the GraphQL playground at `localhost:30
this change is already in

2022-02-21 01:15 UTC, zenweasel commented
Closing to be reopened in a later phase

2022-02-21 01:15 UTC, closed without merging