fix: windows start guide
reactioncommerce/docs pull request #54
Opened 2022-01-25 21:47 UTC by delagroove

2022-02-02 17:33 UTC, MohanNarayana commented on guides/quick-start-windows.md
>    - https://docs.docker.com/desktop/windows/wsl/
Can we make this a sentence and embed the link in text. Something like "Download and install Docker Desktop WSL2 from [here](https://docs.docker.com/desktop/windows/wsl/)"

2022-02-02 17:34 UTC, MohanNarayana requested changes
One change for this

2022-02-02 20:30 UTC, Akarshit approved these changes

2022-02-04 19:35 UTC, delagroove commented on guides/quick-start-windows.md
>    - https://docs.docker.com/desktop/windows/wsl/
moving this to the other guide, shouldn't have 2

2022-02-07 07:22 UTC, zenweasel approved these changes
This is a better approach than a separate Windows Quick Start. Do we have any way of testing any of this?

2022-02-14 01:53 UTC, delagroove commented
@zenweasel it's copied verbatim from @rondlite 's guide. He had tested it.

2022-02-21 01:14 UTC, zenweasel commented
Closing to be reopened in a later phase

2022-02-21 01:14 UTC, closed without merging