Ide guide
reactioncommerce/docs pull request #66
Opened 2022-01-31 23:44 UTC by delagroove

2022-02-01 02:36 UTC, zenweasel commented
@delagroove This is a good start but let's talk about how we can flesh this out and make it more helpful.

2022-02-02 20:33 UTC, Akarshit requested changes

2022-02-02 20:33 UTC, Akarshit commented on docs/setting-your-IDE.md
> +- [Kadira](https://github.com/kadira-open/kadira-server) can help you optimize performance of a Meteor app.
Let's remove Kadira. Also it's only needed for meteor app, which at this point is only Admin.

2022-02-07 07:28 UTC, zenweasel requested changes
Let's have fewer items listed with more info about why you should install them and maybe move the Troubleshooting stuff somewhere else?

2022-02-07 07:28 UTC, zenweasel commented on docs/setting-your-IDE.md
> +- Visual Studio Code is a preferred text editor but you can use Sublime Text, Emacs, Vim or any other editor of your choice.
Let's add Webstorm to this list

2022-02-07 07:28 UTC, zenweasel commented on docs/setting-your-IDE.md
> +- [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)
I think this list should add some context as to why you would want to install these and we might want to break these down a little bit into types of extensions.

2022-02-07 07:28 UTC, zenweasel commented on docs/setting-your-IDE.md
> +### [Visual Studio Code](https://code.visualstudio.com/)
Let's limit these to ones that are more MOC specific and add some info on why you should add them. I think just a list of plugins is not going to be that helpful.

2022-02-07 07:28 UTC, zenweasel commented on docs/setting-your-IDE.md
> +### Memory errors or errors about "Meteor rawLogs"
Not sure how this section is related to setting up your IDE?

2022-02-07 20:13 UTC, MohanNarayana commented on docs/setting-your-IDE.md
> +These are potential issues you might encounter when running Reaction within a local Docker environment using Docker Compose and the docker-compose.yml file.
Name reaction to Open Commerce

2022-02-07 20:14 UTC, MohanNarayana commented on docs/setting-your-IDE.md
> +due to misconfiguration, missing dependencies, operating system differences, and software bugs. Here are some tips for diagnosing and fixing these issues.
Capitalize 'Due'

2022-02-21 01:10 UTC, zenweasel commented
Closing to be reopened in a later phase

2022-02-21 01:10 UTC, closed without merging